# Generated by Django 5.2.4 on 2025-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="joinenddate",
            field=models.IntegerField(),
        ),
    ]
