# Generated by Django 5.2.4 on 2025-07-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_student_joinenddate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fullname',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='staff',
            name='teachingcourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='joinenddate',
            field=models.CharField(max_length=100),
        ),
    ]
