# Generated by Django 5.2.4 on 2025-07-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_fullname_course_staff_teachingcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='joinenddate',
        ),
        migrations.AlterField(
            model_name='staff',
            name='teachingcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.course'),
        ),
    ]
