# Generated by Django 5.2.4 on 2025-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_student_joinenddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=400)),
                ('technologies', models.CharField()),
                ('time', models.CharField(max_length=300)),
            ],
        ),
    ]
