# Generated by Django 5.2.4 on 2025-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='fee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
