# Generated by Django 5.2.4 on 2025-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_data_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salarypermonth',
            field=models.CharField(max_length=100),
        ),
    ]
